/remote_control:
  ros__parameters:
    max_angular_velocity: 3.1415927410125732
    max_linear_velocity: 1.0
    use_sim_time: false

    joy_mapping:
      axis:
        forward: 1
        left: 0
        throttle: 3
        turn: 2

      button: 
        disable: 8
        enable: 9
        indicate_operation: 1
        indicate_parking: 3
        indicate_turn_left: 4
        indicate_turn_right: 5
        indicate_warning: 13
